server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic-mock?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false

project:
  version: @project.version@
dynamic-mock:
  auth:
    jwt:
      pub-key-path: C:\Users\19105\Desktop\rsa\id_rsa.pub
      pri-key-path: C:\Users\19105\Desktop\rsa\id_rsa
