server:
  port: 8080

project:
  version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic-mock?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger使用的配置

