server:
  port: 80

project:
  version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dynamic-mock?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger使用的配置

dynamic-mock:
  admin:
    cors:
      cors-configurations:
        '[/**]':
          allowedOriginPatterns: # 允许哪些网站的跨域请求
            - "*"
          allowedMethods: # 允许的跨域ajax的请求方式
            - "GET"
            - "POST"
            - "DELETE"
            - "PUT"
            - "OPTIONS"
          allowedHeaders: "*" # 允许在请求中携带的头信息
          allowCredentials: true # 是否允许携带cookie
          maxAge: 7200 # 这次跨域检测的有效期
